### PR TITLE
Developer main

### PR DESCRIPTION
**Pull request by Esekyi**
Added Flask-login dependencies and it has reflected in the requirements file.
pushing the login files now

### CODE REVIEW

**Comment by Esekyi** [comment]
Added migrations, user login, logout and fixed errors.

**Comment by Esekyi** [comment]
[fix✍🏼]fixed Add to bag errors `ImportError: no module named Flask-login`

**Comment by Esekyi** [comment]
Please review and i can merge - No errors tho, but confirm

**Comment by Haruna245** [comment]
U can merge it

**Comment by generalgerry** [comment]
Bruv, have we gotten a solution on the hosting yet?

**Comment by Haruna245** [comment]
Yhyh

**Comment by yussifabdulrauf** [comment]
good to merge

**Comment by Praise-Joel** [comment]
Yeah it can be merged

**Pull request merged**
